name: Build DYYY Plugin

on:
  push:
    branches-ignore:
      - dev
  pull_request:
    branches-ignore:
      - dev

jobs:
  build:
    runs-on: macos-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/roothide/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4.2.1
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: huami1314/theos-action@main

      - name: Setup GNU Make
        run: |
          echo "$(brew --prefix)/opt/make/libexec/gnubin" >> $GITHUB_PATH

      - name: Build package
        run: |
          # 清理之前的构建
          rm -rf .theos packages
          # 构建传统版本
          make -j$(sysctl -n hw.ncpu)
          # 构建 Rootless 版本
          make SCHEME=rootless -j$(sysctl -n hw.ncpu)
          # 构建 RootHide 版本
          make SCHEME=roothide -j$(sysctl -n hw.ncpu)

      - name: Upload Deb packages
        uses: actions/upload-artifact@v4.6.0
        with:
          name: DYYY
          path: ${{ github.workspace }}/packages/*.deb
